FORMAT: 1A
HOST: https://api.minepay.net/v1/

# Minepay API

Description coming soon.

## Group Products

Retrieve and update products.

A `Product` object has the following attributes:

+ id - the product ID
+ name - the product name
+ cost - the cost of the product

## Product [/product/{id}]

+ Parameters
    + id (string, required) - the ID of the product you wish to view

### Display Product [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Extra Diamonds",
            "cost": 2.50
        }
        
### Update Product [PUT]
        
Update the properties of a `Product`, you only need to provide the properties you
want to update, omitting the others is fine.

+ Request (application/json)

        {
            "name": "Updated Name",
            "cost": 5.00
        }

+ Response 200 (application/json)

        {
            "updated": [
                "name",
                "cost"
            ]
        }

### Delete Product [DELETE]

+ Response 200 (application/json)

        {
            "message": "Product deletion successful!"
        }


## Product Collection [/product/all]

### All Products [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Extra Diamonds",
                "cost": 2.50
            },
            {
                "id": 2,
                "name": "Extra Emeralds",
                "cost": 5.00
            }
        ]
        
### Create Product [POST]

+ name - the name of the product
+ cost - the cost of the product

+ Request (application/json)
    
        {
            "name": "Extra Arrows",
            "cost": 0.15
        }

+ Response 200 (application/json)

    + Headers
    
            Location: /product/1

    + Body
    
            {
                "message": "Product creation successful!"
                "product": {
                    "id": 1,
                    "name": "Extra Arrows",
                    "cost": 0.15
                }
            }


## Purchased Products [/product/users/{user_id}]

+ Parameters
    
    + user_id (number, required) - the ID of the user
    
### All Products [GET]

+ Response 200 (application/json)

        [
            {
                "id": 5,
                "name": "Veteran Chestplate",
                "cost": 0.00
            }
        ]
        
## Group Categories

A `Category` object has the following properties:

+ id - internal category ID
+ name - category display name

## Category [/category/{id}]

+ id (string, required)

### View Category [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Extra Items"
        }
